#!/bin/bash
#
# Script for removing extra YAML fields for skipped files
#
# Will remove user info, permission info etc for files with "Skip: true"
#
python3 py/triminfo.py <permissions.yml >permissions2.yml
mv -f permissions2.yml permissions.yml
echo git diff permissions.yml
